Repository SkywardAI/kimchima, pull requests merged in 2024-04, with the labels that each got.

#7 Add new command and re-structure project
  .vscode/launch.json
  .vscode/settings.json
  MANIFEST.in
  Makefile
  README.md
  cmds/__init__.py
  examples/examples.py
  pkg/__init__.py
  pkg/auto/__init__.py
  pkg/devices/__init__.py
  pkg/dump/__init__.py
  pkg/dump/dump.py
  pkg/model/__init__.py
  pkg/model/model.py
  pkg/tokenizer/__init__.py
  pkg/tokenizer/tokenizer.py
  pyproject.toml
  src/kimchima/__init__.py
  src/kimchima/cmds/__init__.py
  src/kimchima/cmds/auto_cli.py
  src/kimchima/cmds/kimchima_cli.py
  src/kimchima/pkg/__init__.py
  src/kimchima/pkg/auto.py
  src/kimchima/pkg/devices.py
  src/kimchima/tests/__init__.py
  src/kimchima/tests/test_auto.py
  src/kimchima/tests/test_devices.py
  tests/test_dump.py
  tests/test_tokenizer.py
Labels: enhancement

#9 Optimize poetry
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  Makefile
  README.md
Labels: enhancement, poetry, dev container

#12 WIP: Add logger
  src/kimchima/pipelines/__init__.py
  src/kimchima/pkg/__init__.py
  src/kimchima/pkg/auto.py
  src/kimchima/pkg/logging.py
Labels: enhancement

#19 Redesign the methods by using classmethod
  examples/examples.py
  src/kimchima/__init__.py
  src/kimchima/cmds/__init__.py
  src/kimchima/cmds/auto_cli.py
  src/kimchima/cmds/kimchima_cli.py
  src/kimchima/pkg/__init__.py
  src/kimchima/pkg/auto.py
  src/kimchima/pkg/devices.py
  src/kimchima/pkg/embeddings.py
  src/kimchima/pkg/logging.py
  src/kimchima/pkg/model_factory.py
  src/kimchima/pkg/tokenizer_factory.py
  src/kimchima/tests/test_auto.py
  src/kimchima/tests/test_auto_factory.py
Labels: enhancement, python

#25 Add text iterator streamer
  src/kimchima/pipelines/pipelines_factory.py
  src/kimchima/pkg/streamer_factory.py
Labels: python

#27 Remove quantization for supporting CPU
  examples/embeddings_examples.py
  src/kimchima/pipelines/pipelines_factory.py
  src/kimchima/pkg/model_factory.py
Labels: bug, python, pipeline

#28 remove unsed import
  examples/embeddings_examples.py
Labels: python

#29 Add docs for new class
  poetry.lock
  pyproject.toml
  src/kimchima/__init__.py
  src/kimchima/pipelines/pipelines_factory.py
  src/kimchima/pkg/devices.py
  src/kimchima/pkg/quantization_factory.py
  src/kimchima/pkg/tokenizer_factory.py
Labels: poetry, dependencies, python, minor

#32 Add download model from hf repo
  examples/download_examples.py
  src/kimchima/__init__.py
  src/kimchima/models/__init__.py
  src/kimchima/pkg/__init__.py
  src/kimchima/pkg/download_hub.py
Labels: python, minor

#34 fix release drafter failed on release verision with label
  .github/release-drafter.yml
Labels: bug, ci

#42 poetry release
  .github/release-drafter.yml
  pyproject.toml
Labels: python, ci

#44 Split the release
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: ci

#46 Add chat_summary and add device_map
  examples/embeddings_examples.py
  examples/examples-for-kimchima.ipynb
  src/kimchima/__init__.py
  src/kimchima/pipelines/pipelines_factory.py
  src/kimchima/tests/test_chat.py
  src/kimchima/tests/test_pipelines_factory.py
  src/kimchima/utils/__init__.py
  src/kimchima/utils/chat.py
Labels: python, pipeline

#47 Bump version
  poetry.lock
  pyproject.toml
Labels: poetry, python

#48 piplines instances as parameters of chat summary function
  examples/download_examples.py
  src/kimchima/__init__.py
  src/kimchima/pkg/__init__.py
  src/kimchima/pkg/download_hub.py
  src/kimchima/tests/test_chat.py
  src/kimchima/utils/__init__.py
  src/kimchima/utils/chat.py
  src/kimchima/utils/downloader.py
Labels: pipeline

#69 fix download model issue
  examples/download_examples.py
  src/kimchima/pkg/model_factory.py
  src/kimchima/tests/test_downloadr.py
  src/kimchima/utils/downloader.py
Labels: python, tokenizer, llms, pipeline, patch, quantization

#71 fix/auto_downloader add token file
  .gitignore
  pyproject.toml
  src/kimchima/utils/downloader.py
Labels: python

#72 Re-structure project tree
  examples/README.md
  examples/chat_template_examples.py
  examples/embeddings_examples.py
  examples/examples-for-kimchima.ipynb
  pyproject.toml
  src/kimchima/__init__.py
  src/kimchima/chat_template/__init__.py
  src/kimchima/pipelines/__init__.py
  src/kimchima/pkg/__init__.py
  src/kimchima/pkg/chat_template_factory.py
  src/kimchima/pkg/embedding_factory.py
  src/kimchima/pkg/model_factory.py
  src/kimchima/pkg/pipelines_factory.py
  src/kimchima/pkg/quantization_factory.py
  src/kimchima/pkg/streamer_factory.py
  src/kimchima/pkg/tokenizer_factory.py
  src/kimchima/tests/test_chat.py
  src/kimchima/tests/test_chat_template_factory.py
  src/kimchima/tests/test_downloadr.py
  src/kimchima/tests/test_embedding_factory.py
  src/kimchima/tests/test_model_factory.py
  src/kimchima/tests/test_pipelines_factory.py
  src/kimchima/utils/__init__.py
  src/kimchima/utils/dialog.py
  src/kimchima/utils/downloader.py
Labels: python, llms

#76 fix/chat_summary use conversational input instead of string
  src/kimchima/tests/test_chat.py
  src/kimchima/utils/dialog.py
Labels: python, llms

#77 add dialog and summarize pipeline
  src/kimchima/tests/test_dialog.py
  src/kimchima/utils/dialog.py
  src/kimchima/utils/downloader.py
Labels: python, pipeline, minor
